access:
  user: <username>
  password: <password>
  endpoint: <Polytope URL>

benchmark:
  collection: mchgj  # "mchgj" for feature extraction, "mch" for full field
  param: 500035  # QV
  model: ICON_CH2_EPS  # ICON_CH1_EPS or ICON_CH2_EPS
  levtype: ml  # sfc, ml (model level), pl (pressure level)
  levelist: 74/to/80
  forecast_type: cf  # "pf" (perturbed/ensemble) or "cf" (control)
  num_members: 1  # Ensemble members (20 for CH2, 10 for CH1), ignored if forecast_type == "cf"

  feature:
    type: timeseries  # "timeseries" or "boundingbox"
    # WGS84 coordinates: [[lon, lat], ...] - single point for timeseries, two corners for boundingbox
    points:
      # Zurich Airport
      - [8.565074, 47.453928]
      # Switzerland bounding box
      # - [5.8, 47.81]
      # - [10.5, 45.81]
    range: [0, 120]  # First and last forecast step

  gribjump_log_path: /oprusers/trajond/gribjump-server/logs/log.out  # or null to disable
